from __future__ import annotations

import json
from pathlib import Path

import joblib


class ModelLoader:
    """
    Singleton loader for all ML artifacts.

    Loads and caches:
    - Trained model
    - Preprocessing pipeline
    - Model metadata
    - Transformed feature names
    """

    _model = None
    _preprocessor = None
    _metadata = None
    _feature_names = None

    ARTIFACT_DIR = Path(__file__).parent / "artifacts"

    MODEL_PATH = ARTIFACT_DIR / "best_model.joblib"

    PREPROCESSOR_PATH = (
        ARTIFACT_DIR / "preprocessing_pipeline.joblib"
    )

    METADATA_PATH = (
        ARTIFACT_DIR / "model_metadata.json"
    )

    @classmethod
    def get_model(cls):
        if cls._model is None:

            if not cls.MODEL_PATH.exists():
                raise FileNotFoundError(
                    f"Model not found: {cls.MODEL_PATH}"
                )

            cls._model = joblib.load(
                cls.MODEL_PATH
            )

        return cls._model

    @classmethod
    def get_preprocessor(cls):
        if cls._preprocessor is None:

            if not cls.PREPROCESSOR_PATH.exists():
                raise FileNotFoundError(
                    f"Preprocessor not found: {cls.PREPROCESSOR_PATH}"
                )

            cls._preprocessor = joblib.load(
                cls.PREPROCESSOR_PATH
            )

        return cls._preprocessor

    @classmethod
    def get_metadata(cls):
        if cls._metadata is None:

            if not cls.METADATA_PATH.exists():
                raise FileNotFoundError(
                    f"Metadata not found: {cls.METADATA_PATH}"
                )

            with open(
                cls.METADATA_PATH,
                "r",
                encoding="utf-8",
            ) as f:
                cls._metadata = json.load(f)

        return cls._metadata

    @classmethod
    def get_feature_names(cls):
        """
        Returns transformed feature names generated by the
        preprocessing pipeline.
        """

        if cls._feature_names is None:

            preprocessor = cls.get_preprocessor()

            if not hasattr(
                preprocessor,
                "get_feature_names_out",
            ):
                raise AttributeError(
                    "Preprocessor does not expose "
                    "'get_feature_names_out()'."
                )

            cls._feature_names = (
                preprocessor
                .get_feature_names_out()
                .tolist()
            )

        return cls._feature_names