"""add top_features

Revision ID: 67e80ef0337a
Revises: becd46a91eb9
Create Date: 2026-07-21 00:03:41.343053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67e80ef0337a'
down_revision: Union[str, Sequence[str], None] = 'becd46a91eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('top_features', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'top_features')
    # ### end Alembic commands ###
